# ServiceAccount для доступа к Chaos Mesh Dashboard
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-mesh-admin
  namespace: chaos-mesh
---
# ClusterRole с полными правами для Chaos Mesh
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-mesh-admin
rules:
  - apiGroups: ['']
    resources: ['pods', 'namespaces']
    verbs: ['get', 'watch', 'list']
  - apiGroups: ['chaos-mesh.org']
    resources: ['*']
    verbs: ['get', 'list', 'watch', 'create', 'delete', 'patch', 'update']
---
# ClusterRoleBinding для привязки ServiceAccount к ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-mesh-admin
subjects:
  - kind: ServiceAccount
    name: chaos-mesh-admin
    namespace: chaos-mesh
roleRef:
  kind: ClusterRole
  name: chaos-mesh-admin
  apiGroup: rbac.authorization.k8s.io
---
# Secret для хранения токена ServiceAccount (Kubernetes 1.24+)
apiVersion: v1
kind: Secret
metadata:
  name: chaos-mesh-admin-token
  namespace: chaos-mesh
  annotations:
    kubernetes.io/service-account.name: chaos-mesh-admin
type: kubernetes.io/service-account-token
