apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: myuser
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: test-topic
          patternType: literal
        operations:
          - Read
          - Write
          - Create
          - Describe
      - resource:
          type: group
          name: test-group
          patternType: literal
        operations:
          - Read
