apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: schema-registry
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Cluster-level permissions required by some Kafka clients (e.g. idempotent producer)
      - resource:
          type: cluster
        operations:
          - Describe
          - IdempotentWrite
      # Karapace (Schema Registry API compatible) stores schemas in Kafka topic `_schemas`
      - resource:
          type: topic
          name: _schemas
          patternType: literal
        operations:
          - Read
          - Write
          - Create
          - Describe
          - DescribeConfigs
          - AlterConfigs
      # Consumer group used by Schema Registry
      - resource:
          type: group
          name: schema-registry
          patternType: literal
        operations:
          - Read
          - Describe
      # Karapace may create autogenerated consumer groups (FindCoordinator uses DESCRIBE on group)
      - resource:
          type: group
          name: karapace-autogenerated-
          patternType: prefix
        operations:
          - Read
          - Describe
