# PodMonitor для метрик Strimzi Kafka (Prometheus Operator CRDs)
# ПРИМЕЧАНИЕ: Используем PodMonitor вместо ServiceMonitor, потому что
# Strimzi Kafka 4.x не экспонирует порт tcp-prometheus (9404) в сервисе.
# Метрики доступны только напрямую с подов.
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-cluster
  namespace: kafka-cluster
  labels:
    app: kafka
    strimzi.io/cluster: kafka-cluster
spec:
  selector:
    matchLabels:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
      strimzi.io/name: kafka-cluster-kafka
  namespaceSelector:
    matchNames:
      - kafka-cluster
  podMetricsEndpoints:
    - port: tcp-prometheus
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
# ServiceMonitor для Strimzi Entity Operator (операторы топиков и пользователей)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-entity-operator
  namespace: kafka-cluster
  labels:
    app: kafka-entity-operator
    strimzi.io/cluster: kafka-cluster
spec:
  selector:
    matchLabels:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
      strimzi.io/name: kafka-cluster-entity-operator
  namespaceSelector:
    matchNames:
      - kafka-cluster
  endpoints:
    - port: healthcheck
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
# PodMonitor для Strimzi Cluster Operator
# Экспортирует метрики strimzi_resources, strimzi_reconciliations и др.
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: strimzi-cluster-operator
  namespace: strimzi
  labels:
    app: strimzi-cluster-operator
spec:
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  namespaceSelector:
    matchNames:
      - strimzi
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
