apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: schema-registry
  labels:
    app: schema-registry
spec:
  selector:
    app: schema-registry
  ports:
    - name: http
      port: 8081
      targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: schema-registry
  labels:
    app: schema-registry
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      enableServiceLinks: false
      containers:
        - name: schema-registry
          image: ghcr.io/aiven-open/karapace:latest
          imagePullPolicy: IfNotPresent
          # NOTE: ghcr.io/aiven-open/karapace:latest currently ships a broken console-script entrypoint.
          # Run the module directly instead.
          command: ["python3", "-m", "karapace.__main__"]
          ports:
            - containerPort: 8081
              name: http
          env:
            # Karapace is a Confluent Schema Registry API compatible implementation.
            - name: KARAPACE_KARAPACE_REGISTRY
              value: "true"
            - name: KARAPACE_KARAPACE_REST
              value: "false"
            - name: KARAPACE_HOST
              value: "0.0.0.0"
            - name: KARAPACE_PORT
              value: "8081"
            - name: KARAPACE_ADVERTISED_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KARAPACE_BOOTSTRAP_URI
              value: kafka-cluster-kafka-bootstrap.kafka-cluster:9092
            - name: KARAPACE_SECURITY_PROTOCOL
              value: "PLAINTEXT"
            # - name: KARAPACE_SASL_MECHANISM
            #   value: "SCRAM-SHA-512"
            # - name: KARAPACE_SASL_PLAIN_USERNAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: schema-registry-credentials
            #       key: sasl_plain_username
            # - name: KARAPACE_SASL_PLAIN_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: schema-registry-credentials
            #       key: sasl_plain_password
            - name: KARAPACE_CLIENT_ID
              value: "schema-registry-0"
            - name: KARAPACE_GROUP_ID
              value: "schema-registry"
            - name: KARAPACE_TOPIC_NAME
              value: "_schemas"
          readinessProbe:
            httpGet:
              path: /subjects
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /subjects
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
