# StressChaos: Нагрузка на CPU брокеров Kafka
# Тестирует: Производительность Kafka под нагрузкой на CPU
# Ожидаемый результат: Увеличенная задержка, возможные таймауты, но кластер должен оставаться стабильным
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: kafka-cpu-stress
  namespace: kafka-cluster
spec:
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  stressors:
    cpu:
      workers: 2
      load: 80  # 80% нагрузка на CPU
  duration: "2m"
---
# StressChaos: Высокая нагрузка на CPU (симуляция перегрузки)
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: kafka-cpu-stress-high
  namespace: kafka-cluster
spec:
  mode: all
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  stressors:
    cpu:
      workers: 4
      load: 95  # 95% нагрузка на CPU
  duration: "1m"
