# StressChaos: Нагрузка на CPU брокеров Kafka
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: kafka-cpu-stress
  namespace: kafka-cluster
spec:
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: "2m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: kafka-cpu-stress-high
  namespace: kafka-cluster
spec:
  mode: all
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  stressors:
    cpu:
      workers: 4
      load: 95
  duration: "1m"
