# DNSChaos: Ошибки DNS для брокеров Kafka
apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: kafka-dns-error
  namespace: kafka-cluster
spec:
  action: error
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  patterns:
    - "kafka-cluster-kafka-bootstrap*"
    - "*.kafka-cluster.svc.cluster.local"
  duration: "1m"
---
# DNSChaos: Случайные DNS ответы
apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: kafka-dns-random
  namespace: kafka-cluster
spec:
  action: random
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  patterns:
    - "kafka-cluster-kafka-*"
  duration: "1m"
---
# DNSChaos: Ошибки DNS для producer
apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: kafka-app-dns-error
  namespace: kafka-producer
spec:
  action: error
  mode: all
  selector:
    namespaces:
      - kafka-producer
    labelSelectors:
      app.kubernetes.io/name: kafka-producer
  patterns:
    - "kafka-cluster-kafka-bootstrap.kafka-cluster*"
    - "schema-registry.schema-registry*"
  duration: "1m"
