# HTTPChaos: Задержка ответов Schema Registry
# Тестирует: Поведение Producer/Consumer когда Schema Registry работает медленно
# Ожидаемый результат: Таймауты получения схем, увеличенная задержка
apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: schema-registry-delay
  namespace: schema-registry
spec:
  mode: all
  selector:
    namespaces:
      - schema-registry
    labelSelectors:
      app: schema-registry
  target: Response
  port: 8081
  path: "*"
  delay: "2s"
  duration: "2m"
---
# HTTPChaos: Ошибки 500 от Schema Registry
# Тестирует: Поведение Producer/Consumer когда Schema Registry возвращает ошибки
# Ожидаемый результат: Ошибки получения схем, producer может не отправить сообщение
apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: schema-registry-error
  namespace: schema-registry
spec:
  mode: all
  selector:
    namespaces:
      - schema-registry
    labelSelectors:
      app: schema-registry
  target: Response
  port: 8081
  path: "/subjects/*"
  method: GET
  replace:
    code: 500
    body: "eyJlcnJvcl9jb2RlIjo1MDAwMSwibWVzc2FnZSI6IkludGVybmFsIFNlcnZlciBFcnJvciAoY2hhb3MpIn0="
  duration: "1m"
---
# HTTPChaos: Обрыв соединения Schema Registry
# Тестирует: Поведение Producer/Consumer когда соединение с Schema Registry обрывается
# Ожидаемый результат: Ошибки соединения, повторные попытки
apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: schema-registry-abort
  namespace: schema-registry
spec:
  mode: all
  selector:
    namespaces:
      - schema-registry
    labelSelectors:
      app: schema-registry
  target: Response
  port: 8081
  path: "*"
  abort: true
  duration: "1m"
---
# HTTPChaos: Медленные ответы Kafka UI (для тестирования устойчивости UI)
# Тестирует: Поведение Kafka UI когда backend работает медленно
# Ожидаемый результат: Таймауты UI, ухудшение пользовательского опыта
apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: kafka-ui-delay
  namespace: kafka-ui
spec:
  mode: all
  selector:
    namespaces:
      - kafka-ui
    labelSelectors:
      app.kubernetes.io/name: kafka-ui
  target: Response
  port: 8080
  path: "/api/*"
  delay: "5s"
  duration: "2m"