# IOChaos: Задержка дисковых I/O на брокерах Kafka
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: kafka-io-latency
  namespace: kafka-cluster
spec:
  action: latency
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  volumePath: /var/lib/kafka/data/kafka-log0
  path: "*"
  delay: "100ms"
  percent: 50
  duration: "2m"
---
# IOChaos: Ошибки дискового I/O (EIO)
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: kafka-io-fault
  namespace: kafka-cluster
spec:
  action: fault
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  volumePath: /var/lib/kafka/data/kafka-log0
  path: "*.log"
  errno: 5
  percent: 10
  duration: "1m"
---
# IOChaos: Симуляция заполненного диска (ENOSPC)
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: kafka-io-disk-full
  namespace: kafka-cluster
spec:
  action: fault
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  volumePath: /var/lib/kafka/data/kafka-log0
  path: "*"
  errno: 28
  percent: 100
  methods:
    - write
    - pwrite
  duration: "1m"
