# IOChaos: Задержка дисковых I/O операций на брокерах Kafka
# Тестирует: Производительность Kafka при медленных дисковых операциях
# Ожидаемый результат: Увеличенная задержка produce/fetch, возможные таймауты
# Безопасно: НЕ повреждает данные, только добавляет задержки
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: kafka-io-latency
  namespace: kafka-cluster
spec:
  action: latency
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  volumePath: /var/lib/kafka/data/kafka-log0
  path: "*"
  delay: "100ms"
  percent: 50
  duration: "2m"
---
# IOChaos: Ошибки дискового I/O (EIO - Input/output error)
# Тестирует: Поведение Kafka когда диск возвращает I/O ошибки
# Ожидаемый результат: Брокер может упасть, перевыборы лидера, переназначение партиций
# Безопасно: НЕ повреждает данные, возвращает код ошибки приложению
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: kafka-io-fault
  namespace: kafka-cluster
spec:
  action: fault
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  volumePath: /var/lib/kafka/data/kafka-log0
  path: "*.log"
  errno: 5  # EIO - Ошибка ввода/вывода
  percent: 10
  duration: "1m"
---
# IOChaos: Симуляция заполненного диска (ENOSPC - No space left on device)
# Тестирует: Поведение Kafka когда диск переполнен
# Ожидаемый результат: Ошибки записи, ошибки producer, брокер может стать unhealthy
# Безопасно: НЕ повреждает данные, возвращает код ошибки приложению
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: kafka-io-disk-full
  namespace: kafka-cluster
spec:
  action: fault
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  volumePath: /var/lib/kafka/data/kafka-log0
  path: "*"
  errno: 28  # ENOSPC - Нет места на устройстве
  percent: 100
  methods:
    - write
    - pwrite
  duration: "1m"