# JVMChaos: Принудительный запуск GC на брокерах Kafka
# Тестирует: Поведение Kafka во время сборки мусора
# Ожидаемый результат: Увеличенная задержка, возможные таймауты во время GC
# Примечание: Требуется внедрение JVM агента Chaos Mesh
apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: kafka-jvm-gc
  namespace: kafka-cluster
spec:
  action: gc
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  duration: "30s"
---
# JVMChaos: Нагрузка на CPU в JVM
# Тестирует: Производительность Kafka JVM под нагрузкой на CPU
# Ожидаемый результат: Увеличенная задержка, замедленная обработка
apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: kafka-jvm-cpu-stress
  namespace: kafka-cluster
spec:
  action: stress
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  cpuCount: 2
  duration: "1m"
---
# JVMChaos: Нагрузка на память в JVM (симуляция давления на память)
# Тестирует: Поведение Kafka под нагрузкой на JVM память
# Ожидаемый результат: Более частый GC, возможен OOM
apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: kafka-jvm-memory-stress
  namespace: kafka-cluster
spec:
  action: stress
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  memType: heap
  duration: "1m"
---
# JVMChaos: Внедрение задержки в метод
# Тестирует: Поведение Kafka когда определённые методы работают медленно
# Ожидаемый результат: Увеличенная задержка запросов
# Примечание: Внедряет задержку в метод kafka.log.UnifiedLog.append
apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: kafka-jvm-method-latency
  namespace: kafka-cluster
spec:
  action: latency
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  class: kafka.log.UnifiedLog
  method: append
  latency: 500
  duration: "1m"
---
# JVMChaos: Внедрение исключений
# Тестирует: Поведение Kafka когда методы выбрасывают исключения
# Ожидаемый результат: Обработка ошибок и восстановление
apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: kafka-jvm-exception
  namespace: kafka-cluster
spec:
  action: exception
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  class: kafka.server.KafkaApis
  method: handleProduceRequest
  exception: "java.io.IOException(\"Chaos test exception\")"
  duration: "30s"