# StressChaos: Нагрузка на память брокеров Kafka
# Тестирует: Поведение Kafka под нагрузкой на память
# Ожидаемый результат: Возможные OOM события, паузы GC, деградация производительности
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: kafka-memory-stress
  namespace: kafka-cluster
spec:
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  stressors:
    memory:
      workers: 2
      size: "256MB"
  duration: "2m"
---
# StressChaos: Комбинированная нагрузка на CPU и память
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: kafka-combined-stress
  namespace: kafka-cluster
spec:
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  stressors:
    cpu:
      workers: 2
      load: 60
    memory:
      workers: 1
      size: "128MB"
  duration: "2m"
