# NetworkChaos: Сетевая изоляция одного брокера
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: kafka-network-partition
  namespace: kafka-cluster
spec:
  action: partition
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  direction: both
  duration: "2m"
---
# NetworkChaos: Блокировка трафика между брокерами и producer
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: kafka-producer-partition
  namespace: kafka-cluster
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  direction: both
  target:
    selector:
      namespaces:
        - kafka-producer
      labelSelectors:
        app.kubernetes.io/name: kafka-producer
    mode: all
  duration: "1m"
