# NetworkChaos: Потеря пакетов на брокерах Kafka
# Тестирует: Устойчивость Kafka к ненадёжной сети
# Ожидаемый результат: Увеличенное количество повторных попыток, возможная повторная доставка сообщений
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: kafka-network-loss
  namespace: kafka-cluster
spec:
  action: loss
  mode: all
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  loss:
    loss: "10"
    correlation: "50"
  duration: "2m"
---
# NetworkChaos: Сильная потеря пакетов (деградированная сеть)
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: kafka-network-heavy-loss
  namespace: kafka-cluster
spec:
  action: loss
  mode: all
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  loss:
    loss: "30"
    correlation: "75"
  duration: "1m"
