# NetworkChaos: Добавление сетевой задержки для брокеров Kafka
# Тестирует: Влияние сетевых задержек на производительность producer/consumer
# Ожидаемый результат: Увеличенная задержка сообщений, возможные таймауты
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: kafka-network-delay
  namespace: kafka-cluster
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  delay:
    latency: "100ms"
    jitter: "20ms"
    correlation: "50"
  duration: "2m"
---
# NetworkChaos: Высокая задержка (симуляция кросс-региональной репликации)
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: kafka-network-high-delay
  namespace: kafka-cluster
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  delay:
    latency: "500ms"
    jitter: "100ms"
    correlation: "75"
  duration: "2m"
