# PodChaos: Kill one Kafka broker pod
# Tests: Kafka cluster resilience to broker failure
# Expected: Cluster should remain operational with 2/3 brokers
# Producer/Consumer should reconnect automatically
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kafka-pod-kill
  namespace: kafka-cluster
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  # Duration is not applicable for pod-kill (instant action)
  # Pod will be killed once and recreated by StatefulSet
---
# Schedule: Kill random Kafka broker every 5 minutes (continuous chaos)
# Uses Schedule CRD for Chaos Mesh 2.x
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: kafka-pod-kill-scheduled
  namespace: kafka-cluster
spec:
  schedule: "*/5 * * * *"
  type: PodChaos
  podChaos:
    action: pod-kill
    mode: one
    selector:
      namespaces:
        - kafka-cluster
      labelSelectors:
        strimzi.io/cluster: kafka-cluster
        strimzi.io/kind: Kafka

# todo сделай описание экспериментов на русском языке