# PodChaos: Симуляция сбоя пода (падение контейнера)
# Тестирует: Падение и восстановление брокера Kafka
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kafka-pod-failure
  namespace: kafka-cluster
spec:
  action: pod-failure
  mode: one
  duration: "60s"
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
---
# PodChaos: Симуляция множественных сбоев брокеров (осторожно: может нарушить кворум)
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kafka-multi-pod-failure
  namespace: kafka-cluster
  annotations:
    description: "ВНИМАНИЕ: Это может нарушить кворум кластера"
spec:
  action: pod-failure
  mode: fixed-percent
  value: "60"
  duration: "30s"
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
