# PodChaos: Убийство одного пода брокера Kafka
# Тестирует: Отказоустойчивость кластера Kafka при падении брокера
# Ожидаемый результат: Кластер должен продолжать работу с 2/3 брокерами
# Producer/Consumer должны автоматически переподключиться
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kafka-pod-kill
  namespace: kafka-cluster
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  # Duration не применим для pod-kill (мгновенное действие)
  # Под будет убит однократно и пересоздан StatefulSet
---
# Schedule: Убийство случайного брокера Kafka каждые 5 минут (непрерывный хаос)
# Использует Schedule CRD для Chaos Mesh 2.x
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: kafka-pod-kill-scheduled
  namespace: kafka-cluster
spec:
  schedule: "*/5 * * * *"
  type: PodChaos
  podChaos:
    action: pod-kill
    mode: one
    selector:
      namespaces:
        - kafka-cluster
      labelSelectors:
        strimzi.io/cluster: kafka-cluster
        strimzi.io/kind: Kafka