# PodChaos: Симуляция сбоя одного брокера (ISR сохраняется)
# Тестирует: Падение и восстановление одного брокера; ISR >= min.insync.replicas (2)
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kafka-pod-failure
  namespace: kafka-cluster
spec:
  action: pod-failure
  mode: one
  duration: "60s"
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/pool-name: broker
---
# PodChaos: Сбой 2 из 3 брокеров — нарушение min.insync.replicas
# Тестирует: ISR < min.insync.replicas, запись блокирована, чтение возможно.
# После восстановления: ISR восстанавливается, запись возобновляется.
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kafka-multi-pod-failure
  namespace: kafka-cluster
  annotations:
    description: "2 из 3 брокеров недоступны — ISR нарушен"
spec:
  action: pod-failure
  mode: fixed
  value: "2"
  duration: "60s"
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/pool-name: broker
