# TimeChaos: Clock skew on Kafka brokers
# Tests: Kafka behavior when system time is shifted
# Expected: Possible issues with log segments, retention, timestamps
# Note: Kafka uses timestamps for log retention and message ordering
apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: kafka-time-skew
  namespace: kafka-cluster
spec:
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  timeOffset: "5m"  # Shift time forward by 5 minutes
  duration: "2m"
---
# TimeChaos: Large clock skew (simulate NTP failure)
# Tests: Kafka behavior with significant time drift
# Expected: May trigger log segment rotation, retention issues
apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: kafka-time-skew-large
  namespace: kafka-cluster
spec:
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  timeOffset: "-1h"  # Shift time backward by 1 hour
  duration: "1m"
---
# TimeChaos: Clock skew between brokers (split-brain time)
# Tests: Cluster behavior when brokers have different times
# Expected: Possible leader election issues, message ordering problems
apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: kafka-time-skew-partial
  namespace: kafka-cluster
spec:
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    fieldSelectors:
      metadata.name: kafka-cluster-mixed-0
  timeOffset: "10m"  # Only one broker has time shifted
  duration: "2m"

# todo сделай описание экспериментов на русском языке