# TimeChaos: Смещение времени на брокерах Kafka
apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: kafka-time-skew
  namespace: kafka-cluster
spec:
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  timeOffset: "5m"
  duration: "2m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: kafka-time-skew-large
  namespace: kafka-cluster
spec:
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  timeOffset: "-1h"
  duration: "1m"
---
# TimeChaos: Смещение времени только на одном брокере
apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: kafka-time-skew-partial
  namespace: kafka-cluster
spec:
  mode: one
  selector:
    namespaces:
      - kafka-cluster
    fieldSelectors:
      metadata.name: kafka-cluster-kafka-0
  timeOffset: "10m"
  duration: "2m"
