---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: entity-operator-metrics
  labels:
    app: strimzi
    release: vmks
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: entity-operator
  namespaceSelector:
    matchNames:
      - kafka-cluster
  podMetricsEndpoints:
    - path: /metrics
      port: healthcheck
