apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: test-topic
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 1
  replicas: 3
  config:
    # retention.ms: 2 часа (по умолчанию -1 = бесконечное хранение)
    # Короткое время для быстрого наблюдения эффектов chaos-тестов и контроля диска
    retention.ms: 7200000
