# KafkaUser для Schema Registry (Karapace)
# Отдельный пользователь с минимальными правами для топика _schemas и consumer groups
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: schema-registry
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Cluster-level: Describe, IdempotentWrite (требуется некоторыми Kafka клиентами)
      - resource:
          type: cluster
        operations:
          - Describe
          - IdempotentWrite
        host: "*"
      # Karapace хранит схемы в топике _schemas
      - resource:
          type: topic
          name: _schemas
          patternType: literal
        operations:
          - Read
          - Write
          - Create
          - Describe
          - DescribeConfigs
          - AlterConfigs
        host: "*"
      # Consumer group Schema Registry
      - resource:
          type: group
          name: schema-registry
          patternType: literal
        operations:
          - Read
          - Describe
        host: "*"
      # Karapace создаёт автосгенерированные consumer groups (karapace-autogenerated-*)
      - resource:
          type: group
          name: karapace
          patternType: prefix
        operations:
          - Read
          - Describe
        host: "*"
