# PodDisruptionBudget для брокеров Kafka
# Гарантирует, что минимум 2 брокера всегда доступны во время плановых прерываний
# (drain ноды, обновление кластера, rolling updates)
# minAvailable: 2 поддерживает кворум для min.insync.replicas: 2
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kafka-cluster-pdb
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  minAvailable: 2
  selector:
    matchLabels:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
      strimzi.io/name: kafka-cluster-broker
