apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: kafka-ui-user
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Разрешение на чтение всех топиков (для просмотра сообщений)
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operations:
          - Describe
          - Read
        host: "*"
      # Разрешение на работу с consumer groups
      - resource:
          type: group
          name: "*"
          patternType: literal
        operations:
          - Describe
          - Read
        host: "*"
      # Разрешение на просмотр информации о кластере
      - resource:
          type: cluster
        operations:
          - Describe
          - DescribeConfigs
        host: "*"
