apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: myuser
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Разрешаем доступ ко всем топикам, чтобы приложения могли писать/читать
      # даже если клиент/брокер используют topicId (в логах Kafka это иногда выглядит как пустое имя).
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operations:
          - Read
          - Write
          - Create
          - Describe
          - DescribeConfigs
          - AlterConfigs
      - resource:
          type: topic
          name: test-topic
          patternType: literal
        operations:
          - Read
          - Write
          - Create
          - Describe
          - DescribeConfigs
          - AlterConfigs
      - resource:
          type: cluster
        operations:
          - Describe
          - IdempotentWrite
      - resource:
          type: group
          name: test-group
          patternType: literal
        operations:
          - Read
      - resource:
          type: group
          name: "*"
          patternType: literal
        operations:
          - Read
