# PodDisruptionBudget для брокеров Kafka
# Гарантирует, что минимум 2 брокера всегда доступны во время плановых прерываний
# (например, drain ноды, обновление кластера, rolling updates)
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kafka-cluster-pdb
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  # minAvailable: 2 гарантирует поддержание кворума для min.insync.replicas: 2
  minAvailable: 2
  selector:
    matchLabels:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
      strimzi.io/name: kafka-cluster-mixed
