apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.1.1
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
    authorization:
      type: simple
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    # JSON logging format for Kafka brokers
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: INFO
        log4j.appender.CONSOLE: org.apache.log4j.ConsoleAppender
        log4j.appender.CONSOLE.layout: net.logstash.log4j.JSONEventLayoutV1
  entityOperator:
    topicOperator:
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO
          rootLogger.appenderRef.console.ref: STDOUT
          appender.console.type: Console
          appender.console.name: STDOUT
          appender.console.layout.type: JsonTemplateLayout
          appender.console.layout.eventTemplateUri: classpath:EcsLayout.json
    userOperator:
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO
          rootLogger.appenderRef.console.ref: STDOUT
          appender.console.type: Console
          appender.console.name: STDOUT
          appender.console.layout.type: JsonTemplateLayout
          appender.console.layout.eventTemplateUri: classpath:EcsLayout.json
