apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: myuser
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Example consumer Acls for topic test-topic using consumer group test-group
      - resource:
          type: topic
          name: test-topic
          patternType: literal
        operations:
          - Describe
          - Read
        host: "*"
      - resource:
          type: group
          name: test-group
          patternType: literal
        operations:
          - Read
        host: "*"
      # Example Producer Acls for topic test-topic
      - resource:
          type: topic
          name: test-topic
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
        host: "*"
