# Redis exporter для сбора метрик Yandex Managed Redis (Valkey).
# Используется для мониторинга latency, нагрузки и доступности Redis (docs/delivery-verification-critique.md).
#
# Перед применением создайте Secret с адресом и паролем Valkey (например из terraform output external_valkey):
#   kubectl create secret generic valkey-exporter-redis -n vmks \
#     --from-literal=REDIS_ADDR='c-<cluster_id>.rw.mdb.yandexcloud.net:6379' \
#     --from-literal=REDIS_PASSWORD='<password>'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: vmks
  labels:
    app.kubernetes.io/name: redis-exporter
    app.kubernetes.io/component: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-exporter
        app.kubernetes.io/component: exporter
    spec:
      containers:
        - name: redis-exporter
          image: quay.io/oliver006/redis_exporter:v1.55.0
          args:
            - --web.listen-address=:9121
          env:
            - name: REDIS_ADDR
              valueFrom:
                secretKeyRef:
                  name: valkey-exporter-redis
                  key: REDIS_ADDR
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: valkey-exporter-redis
                  key: REDIS_PASSWORD
          ports:
            - name: http
              containerPort: 9121
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: vmks
  labels:
    app.kubernetes.io/name: redis-exporter
spec:
  selector:
    app.kubernetes.io/name: redis-exporter
  ports:
    - name: http
      port: 9121
      targetPort: 9121
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: redis-exporter
  namespace: vmks
  labels:
    release: vmks
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-exporter
  namespaceSelector:
    matchNames:
      - vmks
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
