# Redis exporter для in-cluster Redis (redis/redis.yaml).
# Метрики для дашборда redis-delivery-verification в Grafana.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter-in-cluster
  namespace: vmks
  labels:
    app.kubernetes.io/name: redis-exporter-in-cluster
    app.kubernetes.io/component: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-exporter-in-cluster
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-exporter-in-cluster
        app.kubernetes.io/component: exporter
    spec:
      containers:
        - name: redis-exporter
          image: quay.io/oliver006/redis_exporter:v1.55.0
          args:
            - --web.listen-address=:9121
          env:
            - name: REDIS_ADDR
              value: "redis.redis.svc.cluster.local:6379"
          ports:
            - name: http
              containerPort: 9121
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter-in-cluster
  namespace: vmks
  labels:
    app.kubernetes.io/name: redis-exporter-in-cluster
spec:
  selector:
    app.kubernetes.io/name: redis-exporter-in-cluster
  ports:
    - name: http
      port: 9121
      targetPort: 9121
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: redis-exporter-in-cluster
  namespace: vmks
  labels:
    release: vmks
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-exporter-in-cluster
  namespaceSelector:
    matchNames:
      - vmks
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
